### ISSUE TITLE
10.9 Incompatibility

### ISSUE THREAD

**Issue by Zoft123** [BobHasNoSoul/jellyfin-featured#5]
I have 2 different servers I have this added to, one is on 18.3, the other is on 19.0 and was simply reporting that it appears this no longer works with 19.0 going forward. Which is odd because while the mapped home.js file is still used in the docker image, applying the changes as you would previously for 18.3 and restarting the docker container, the featured bar simply just doesn't appear.

**Comment by BobHasNoSoul** [comment]
i will get on this when i have some free time from work, and when i can get a final build of 19.0 that is stable (the reason for this is they like to change variables in the code that breaks a lot of things in unstable builds.. one of the main reasons that killed jftool) any news on when it should release as a stable

**Comment by Zoft123** [comment]
Not that I'm aware of, kind of regret trying out the 19.0 on my other server as in it's current state IPTV is broken as well. Same XMLTV and M3U tuner on both servers, 18.3 works A-OK, 19.0 throws fatal error. :|

**Comment by BobHasNoSoul** [comment]
update: 10.9 released 

if you do a standard over the top upgrade it works out the box.. going to make a brand new install on a test rig to be able to check if it is just my config or something deeper that was changed

**Comment by BobHasNoSoul** [comment]
update i can get it to show and generate but they changed something with the api i need more time to look into for grabbing the descriptions... all of my requests with old style api request fail with malformed request on the overview option... hmm

**Comment by BobHasNoSoul** [comment]
update it should work now please pull the new files `make.sh` `featuredstyles.css` `featuredscripts.js` and if you are using docker you should check the uuid for the home-html has not changed in the update using docker shell or by using the steps of mounting webroot directly outlined in the fix for the other related bug here https://github.com/BobHasNoSoul/jellyfin-featured/issues/6 once done clear your cache and reload the page

let me know how it goes here is a screen of my 10.9.0 install, currently taking free time to port all the mods i can over but will do most of them at the weekend.

<img width="960" alt="Screenshot 2024-05-14 222821" src="https://github.com/BobHasNoSoul/jellyfin-featured/assets/23018412/c33f116f-4112-4e12-8ebe-ef6c3bd600f7">
